@startuml
!include style.puml

start
:Request redo;
if() then ([CommandHistory contains commands])
    :Retrieve task from CommandHistory;
    if() then ([Task can be redone])
        :Call execute() method of task;
        :Return redo() command message;
    else([Task cannot be redone])
        :Return error message to user;
    endif
else([CommandHistory is empty])
    :Return error message to user;
endif
:Recompute task filters and update GUI;
stop

@enduml
