@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
}

package "TaskList Storage" #F4F6F6{
Interface "TaskListStorage" <<Interface>>
Class JsonTaskListStorage
Class JsonSerializableTaskList
Class JsonAdaptedTask
}

Class JsonAdaptedTag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -up-> "1" TaskListStorage

Storage --|> UserPrefsStorage
Storage --|> AddressBookStorage
Storage --|> TaskListStorage


JsonUserPrefsStorage .up.|> UserPrefsStorage

JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

JsonTaskListStorage .up.|> TaskListStorage
JsonTaskListStorage ..> JsonSerializableTaskList
JsonSerializableTaskList --> "*" JsonAdaptedTask
JsonAdaptedTask --> "*" JsonAdaptedTag

@enduml
